<a href="https://colab.research.google.com/github/omkar3103/Python_Core_Practice_codes/blob/main/Numpy_Pyhton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🔹 Part 1: Basic Level
Q1️⃣ Create Arrays

Create a 1D NumPy array from 1 to 10.

Create a 3×3 matrix filled with zeros.

Create a 4×4 matrix filled with ones.

Create an array from 10 to 50 with step 5.

Create a 3×3 identity matrix.

In [1]:
import numpy as np

Create a 1D NumPy array from 1 to 10.

In [5]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a_1=np.arange(1,10)

Create a 3×3 matrix filled with zeros.

In [6]:
print(a)
print(a_1)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8 9]


Create a 4×4 matrix filled with ones.

In [8]:
b= np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create an array from 10 to 50 with step 5.

In [9]:
ones=np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create a 3×3 identity matrix.

In [10]:
identity_mat = np.eye(3,3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q2️⃣ Array Properties

In [33]:
arr = np.array([[10,20,30],[40,50,60]])

In [38]:
print(arr)
print(arr.shape) #Print Shape of array
print(arr.size) #print total Size of array
print(arr.dtype) #Print Type of array
print(arr.ndim) #Print Dimensions of array

[[10 20 30]
 [40 50 60]]
(2, 3)
6
int64
2


Q3️⃣ Indexing & Slicing

In [40]:
a = np.array([5,10,15,20,25,30])

Extract first 3 elements

Extract last 2 elements

Reverse the array

In [49]:
print(a[1:4])     #Extract first 3 elements
print(a[-1:3:-1]) #Extract last 2 elements
print(a[::-1])    #Reverse the array

[10 15 20]
[30 25]
[30 25 20 15 10  5]


🔹 Part 2: Intermediate Level

Q4️⃣ Random Arrays

Create a 3×3 matrix of random numbers between 0 and 1

Find:

Maximum value

Minimum value

Mean

Standard deviation

In [50]:
rand_arr = np.random.randint(1,10,size=(3,3))
print(rand_arr)

[[4 4 4]
 [9 2 6]
 [8 3 6]]


In [52]:
print(rand_arr.max())  #Maximum value
print(rand_arr.min())  #Minimum value
print(rand_arr.mean()) #Mean
print(rand_arr.std())  #Standard deviation

9
2
5.111111111111111
2.1829869671542776


Q5️⃣ Reshaping

Convert into 3×4 matrix

Convert into 4×3 matrix

Convert into 2×6 matrix

In [53]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [56]:
a_3x4=a.reshape(3,4) #Convert into 3×4 matrix
print(a_3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
a_4x3=a.reshape(4,3) #Convert into 4×3 matrix
print(a_4x3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [58]:
a_2x6=a.reshape(2,6) #Convert into 2×6 matrix
print(a_2x6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Q6️⃣ Boolean Masking

Extract elements greater than 20

Replace elements less than 20 with 0

In [59]:
arr = np.array([10,15,20,25,30,35])

In [61]:
for i in arr:
  if i>20:
    print(i,'')

25 
30 
35 


In [65]:
arr[arr<20] = 0
print(arr)

[ 0  0 20 25 30 35]


🔹 Part 3: Advanced Level (Important for ML)

In [66]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])

In [68]:
print(a+b) #Add both arrays

[[11 12 13]
 [21 22 23]
 [31 32 33]]


Q8️⃣ Matrix Operations

Create two 3×3 matrices and:

Add them

Subtract them

Multiply element-wise

Perform matrix multiplication

Find transpose

In [78]:
a_1=np.array([[10,20,30],[40,30,50],[60,70,80]])
b_1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [80]:
print(a_1.ndim)
print(b_1.ndim)

2
2


In [81]:
print(a_1)

[[10 20 30]
 [40 30 50]
 [60 70 80]]


In [82]:
print(a_1+b_1)

[[11 22 33]
 [44 35 56]
 [67 78 89]]


In [83]:
print(a_1-b_1)

[[ 9 18 27]
 [36 25 44]
 [53 62 71]]


In [84]:
print(a_1*b_1)

[[ 10  40  90]
 [160 150 300]
 [420 560 720]]


In [85]:
print(a_1.dot(b_1))

[[ 300  360  420]
 [ 510  630  750]
 [ 900 1110 1320]]


In [88]:
print(np.transpose(a_1))

[[10 40 60]
 [20 30 70]
 [30 50 80]]


In [89]:
print(np.transpose(b_1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Q9️⃣ Mini ML-Type Question

Create a 5×3 dataset (5 rows = students, 3 columns = marks in subjects).

Find average marks per student

Find average marks per subject

Find student with highest total marks